#Hubbibi Config

#General Navigator Settings
navigator:
  name: '&cNavigator'
  item: 'ENDER_PEARL'
  inv-slot: 4
  inv-size: 27

#Navigator Content
navigator-warps:
  spawn:
    slot: 13
    item: 'SLIME_BALL'
    name: '&cSpawn'
    coordinates:
      x: -30.5
      y: 127
      z: -211.5
    lore:

  featured:
    slot: 11
    item: 'FIREWORK_ROCKET'
    name: '&dFeatured'
    coordinates:
      x: -34
      y: 119
      z: -186.1
    lore:

  arcade:
    slot: 15
    item: 'CLOCK'
    name: '&dArcade'
    coordinates:
      x: -78.5
      y: 122
      z: -176.5
    lore:

    skywars:
      slot: 3
      item: 'GRASS_BLOCK'
      name: '&bSkywars'
      coordinates:
        x: -11.5
        y: 132
        z: -140
      lore:

    jumpy:
      slot: 5
      item: 'DIAMOND_BOOTS'
      name: '&aJumpy'
      coordinates:
        x: -13
        y: 122
        z: -178
      lore: